### ISSUE TITLE
Wrong/ incomplete Dockerfile!?

### ISSUE THREAD

**Issue by x-sven** [bemasher/rtl-sdr#1]
g++ missing, container not running at all:

...
Error loading shared library librtlsdr.so.0: No such file or directory (needed by /usr/local/bin/rtl_tcp)
Error relocating /usr/local/bin/rtl_tcp: rtlsdr_get_device_count: symbol not found
Error relocating /usr/local/bin/rtl_tcp: rtlsdr_reset_buffer: symbol not found
Error relocating /usr/local/bin/rtl_tcp: rtlsdr_get_tuner_gains: symbol not found
Error relocating /usr/local/bin/rtl_tcp: rtlsdr_set_offset_tuning: symbol not found
Error relocating /usr/local/bin/rtl_tcp: rtlsdr_set_direct_sampling: symbol not found
Error relocating /usr/local/bin/rtl_tcp: rtlsdr_set_tuner_if_gain: symbol not found
...

**Comment by bemasher** [comment]
Sorry about that. This repo and its code is ancient, I don't recommend anyone use this for any reason.

**Comment by x-sven** [comment]
THX, better remove this then: https://hub.docker.com/r/bemasher/rtl-sdr

Image is still working but container cannot be build :-)

**Comment by bemasher** [comment]
Will do.
